#!/usr/bin/sh
# This script highlights places where DW_OP_bra, DW_OP_skip, DW_OP_call2, DW_OP_call4, and DW_OP_ref
# used.

if [ "$#" -ne 1 ]; then
    echo "Expect a path to a file to analyze" >&2
    exit 1
fi

# List out any location list entries with branching operations
dwgrep "$1" -e '
let A := entry (?TAG_subprogram || ?TAG_inlined_subroutine) (?AT_ranges || ?AT_low_pc);
let FSTART := ((A ?AT_entry_pc @AT_entry_pc) || (A ?AT_ranges @AT_ranges low) || ( A low));
let VAR := (A child (?TAG_formal_parameter || ?TAG_variable));
let BRANCH := (VAR @AT_location (?DW_OP_bra || ?DW_OP_skip || ?DW_OP_call2 || ?DW_OP_call4 || ?DW_OP_call_ref));
[A name, FSTART, VAR name, BRANCH]' | grep "\["
