#!/usr/bin/sh
if [ "$#" -ne 1 ]; then
    echo "Expect a path to a file to analyze" >&2
    exit 1
fi

dwgrep "$1" -e '
let A := entry (?TAG_subprogram || ?TAG_inlined_subroutine) !AT_declaration;
let FSTART := ((A ?AT_entry_pc @AT_entry_pc) || (A ?AT_ranges @AT_ranges low) || ( A low));
let B := [A child ?TAG_formal_parameter name] ;
let ABS_ORIGIN := A @AT_abstract_origin;
let C := [ABS_ORIGIN child ?TAG_formal_parameter name];
(C length != B length) [FSTART, A name, C, B]'
