#!/usr/bin/sh
if [ "$#" -ne 1 ]; then
    echo "Expect a path to a file to analyze" >&2
    exit 1
fi

dwgrep "$1" -e '
let A := entry (?TAG_subprogram || ?TAG_inlined_subroutine) (?AT_ranges || ?AT_low_pc);
let FSTART := ((A ?AT_entry_pc @AT_entry_pc) || (A ?AT_ranges @AT_ranges low) || ( A low));
let PARM := (A child ?TAG_formal_parameter);
let LOCS := [PARM @AT_location];
(LOCS length == 0) [A name, FSTART, PARM name]'
